server {
    listen 80;

    # Frontend (Vite build)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    # Backend API routes
    location /api/ {
        proxy_pass http://backend:8080;
    }

    location /auth/ {
        proxy_pass http://backend:8080;
    }

    # Đổi thành /proxy-admin/ để tránh đụng chạm với React Router /admin/
    location /proxy-admin/ {
        # proxy_pass có URI cụ thể sẽ giúp Nginx cắt /proxy-admin/ và thế bằng /admin/
        proxy_pass http://backend:8080/admin/;
    }
}