# spring.application.name=DoantotnghiepIJ
# server.port=${PORT:8080}
# spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:doantotnghiep}
# spring.datasource.username=${PGUSER:postgres}
# spring.datasource.password=${PGPASSWORD:123456}
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# services.product.url=http://localhost:8080
# openai.api.key=${OPENAI_API_KEY:test}
# vnpay.tmnCode=R9Z0NWKB
# vnpay.secretKey=DAQPKGAE0DRAX8MPRKTS5JAAF0G9E1OS
# vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
# vnpay.returnUrl=http://localhost:8080/api/payment/vnpay-return
# vietqr.accountNo=5811649739
# vietqr.accountName=TRAN VAN TUNG
# vietqr.bankCode=970418


spring.application.name=DoantotnghiepIJ
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://postgres:5432/doantotnghiep
spring.datasource.username=postgres
spring.datasource.password=VanTung2211@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

services.product.url=http://backend:8080
openai.api.key=${OPENAI_API_KEY}
vnpay.tmnCode=R9Z0NWKB
vnpay.secretKey=DAQPKGAE0DRAX8MPRKTS5JAAF0G9E1OS
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8080/api/payment/vnpay-return
vietqr.accountNo=5811649739
vietqr.accountName=TRAN VAN TUNG
vietqr.bankCode=970418

###
#spring.application.name=DoantotnghiepIJ
#server.port=9090
#spring.datasource.url=jdbc:postgresql://localhost:5432/doantotnghiep_db
#spring.datasource.username=tung
#spring.datasource.password=123456
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#services.product.url=http://103.82.24.142:9090

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tranvantung513@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
